config/routes.rb
LearnDota::Application.routes.draw do

  resources :guides do
    resources :votes
  end

  resources :users

  resources :skills

  resources :heros
  root 'heros#index'

  

end

app/models/hero.rb
class Hero < ActiveRecord::Base
  has_many :guides
  has_many :skills
  validates_presence_of :name
  validates_uniqueness_of :name
  validates :oftype, inclusion: { in: %w(Strength Agility Intelligence),
                                  message: "should be Strength,Agility,Intelligence" }
  validates_presence_of :faction
  validates :faction, inclusion: { in: %w(Radiant Dire),
                                   message: "should be Radiant,Dire" }
  validates_presence_of :melrange
  validates :melrange, inclusion: { in: %w(Melee Range),
                                    message: "should be Melee,Range" }

end

app/controllers/heros_controller.rb
class HerosController < ApplicationController
  before_action :set_hero, only: [:show, :edit, :update, :destroy]

  # GET /heros
  # GET /heros.json
  def index
    @heros = Hero.all
  end

  # GET /heros/1
  # GET /heros/1.json
  def show
  end

  # GET /heros/new
  def new
    @hero = Hero.new
  end

  # GET /heros/1/edit
  def edit
  end

  # POST /heros
  # POST /heros.json
  def create
    @hero = Hero.new(hero_params)

    respond_to do |format|
      if @hero.save
        format.html { redirect_to @hero, notice: 'Hero was successfully created.' }
        format.json { render action: 'show', status: :created, location: @hero }
      else
        format.html { render action: 'new' }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heros/1
  # PATCH/PUT /heros/1.json
  def update
    respond_to do |format|
      if @hero.update(hero_params)
        format.html { redirect_to @hero, notice: 'Hero was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heros/1
  # DELETE /heros/1.json
  def destroy
    @hero.destroy
    respond_to do |format|
      format.html { redirect_to heros_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hero
      @hero = Hero.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hero_params
      params.require(:hero).permit(:name, :oftype, :faction, :melrange, :hasguide)
    end
end

app/helpers/heros_helper.rb
module HerosHelper
end

app/views/heros/_form.html.erb
<%= form_for(@hero) do |f| %>
  <% if @hero.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hero.errors.count, "error") %> prohibited this hero from being saved:</h2>

      <ul>
      <% @hero.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :oftype %><br>
    <%= f.text_field :oftype %>
  </div>
  <div class="field">
    <%= f.label :faction %><br>
    <%= f.text_field :faction %>
  </div>
  <div class="field">
    <%= f.label :melrange %><br>
    <%= f.text_field :melrange %>
  </div>
  <div class="field">
    <%= f.label :hasguide %><br>
    <%= f.check_box :hasguide %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/heros/edit.html.erb
<h1>Editing hero</h1>

<%= render 'form' %>

<%= link_to 'Show', @hero %> |
<%= link_to 'Back', heros_path %>

app/views/heros/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3>Strength</h3>
  </div>
<div class="panel-body">
  <div class="row">
    <% @heros.each do |hero| %>
        <% if hero.oftype=="Strength" %>
            <div class="col-xs-6 col-md-4">
                <%= link_to image_tag(hero.name+".jpg",:class=>"thumbnail"),hero%>
              <h4><%= hero.name %></h4>
              <p>
                <%= hero.faction %> |
                <%= hero.melrange %> |
                <%= hero.oftype %> |
              </p>
            </div>
        <%end%>
    <% end %>
    </div>
</div>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3>Agility</h3>
  </div>
  <div class="panel-body">
    <div class="row">
      <% @heros.each do |hero| %>
          <% if hero.oftype=="Agility" %>
              <div class="col-xs-6 col-md-4">
                <%= link_to image_tag(hero.name+".jpg",:class=>"thumbnail"),hero%>
                <h4><%= hero.name %></h4>
                <p>
                  <%= hero.faction %> |
                  <%= hero.melrange %> |
                  <%= hero.oftype %> |
                </p>
              </div>
          <%end%>
      <% end %>
    </div>
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3>Intelligence</h3>
  </div>
  <div class="panel-body">
    <div class="row">
      <% @heros.each do |hero| %>
          <% if hero.oftype=="Intelligence" %>
              <div class="col-xs-6 col-md-4">
                <%= link_to image_tag(hero.name+".jpg",:class=>"thumbnail"),hero%>
                <h4><%= hero.name %></h4>
                <p>
                  <%= hero.faction %> |
                  <%= hero.melrange %> |
                  <%= hero.oftype %> |
                </p>
              </div>
          <%end%>
      <% end %>
    </div>
  </div>
</div>

app/views/heros/new.html.erb
<h1>New hero</h1>

<%= render 'form' %>

app/views/heros/show.html.erb
<div class="row">
  <div class="col-lg-3">
    <div class="panel panel-default">
      <div class="panel-heading"><%= @hero.name %></div>
      <div class="panel-body">
        <%= image_tag(@hero.name+".jpg", :class => "thumbnail") %>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">Guide</div>
      <div class="panel-body">
        </p>
            <em><%= link_to 'Click here to add a guide', new_guide_path %></em>
        <% if @hero.guides.size != 0 %>
            <% @hero.guides.each do |guide| %>
                <p>
                <li><strong><em><%= link_to 'Guide', guide %> by <%== guide.user_id %></em></strong>
                </p>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-lg-9">
    <div class="panel panel-default">
      <div class="panel-heading">Stats</div>
      <div class="panel-body">
        <p>
          <strong>Type:</strong>
          <%= @hero.oftype %>
        </p>
        <p>
          <strong>Faction:</strong>
          <%= @hero.faction %>
        </p>
        <p>
          <strong>Melee/Range:</strong>
          <%= @hero.melrange %>
        </p>

        <p>
          <strong>Skills:</strong>
        <ul>
          <% @hero.skills.each do |skill| %>
              <p>
              <li>Skill <%== skill.skillnum %>: <%= skill.sname %>
                <% if skill.ultimate == 1 %>
                    <em>(Ultimate)</em>
                <% end %>
                <ul>
                  <li><%== skill.description %></ul>
              </p>
          <% end %>
          <% if @hero.skills.size == 0 %>
              <em class="alert-danger">No skills found.Will be added shortly</em>
          <% end %>
          </ul>
          </div>
    </div>
  </div>
</div>
<p id="notice"><%= notice %></p>