config/routes.rb
LearnDota::Application.routes.draw do

  resources :guides do
    resources :votes
  end

  resources :users

  resources :skills

  resources :heros
  root 'heros#index'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LearnDota</title>
  <style>
      body {
          padding-top: 70px;
      }
  </style>
  <%= stylesheet_link_tag "bootstrap" %>
  <%= stylesheet_link_tag media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body style>
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">LearnDota</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="actice"><a href=<%= heros_path %>>Heros</a></li>
        <li><a href=<%= guides_path %>>Guides</a></li>
      </ul>
      <form class="navbar-form navbar-right">
        <!-- <img src="assets/signin.png" width="90px" height="35px"></img>   -->
        <button type="submit" class="btn btn-success">Sign in</button>
      </form>
    </div>
    <!--/.navbar-collapse -->
  </div>
</div>
<section>
  <div class="jumbotron" style="margin-top:-20px"> <!--background-image: url('assets/Fire.jpg'); background-position: 30%" >    -->
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-lg-12">
          <h1>Learn Dota</h1>

          <p>Your destination for the best Dota rosters and guides.</p>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <%= yield %>
  </div>
</section>
</body>
</html>